name: "precompile quickjs and upload artifact"
description: "precompile `libquickjs.a` as a static library on the host system, then upload it as an artifact."
inputs:
  host-platform:
    description: "the host platform must be one of: ['windows_amd64', 'linux_amd64', 'darwin_amd64']"
    required: true
    default: "linux_amd64"
outputs:
  artifact-url:
    description: "the url of the static library artifact that was compiled."
    value: ${{ steps.upload-artifact.outputs.artifact-url }}

runs:
  using: "composite"
  steps:
    - name: "update submodule"
      shell: "bash"
      run: |
        cd "./vendor/quickjs/"
        git fetch origin
        git checkout origin/HEAD

    - name: "compile libquickjs.a"
      shell: "bash"
      env:
        HOST_PLATFORM: ${{ inputs.host-platform }}
      run: |
        cd "./vendor/quickjs/"
        make clean
        make libquickjs.a

    - name: "upload artifact"
      id: "upload-artifact"
      uses: "actions/upload-artifact@v6"
      with:
        name: "${{ inputs.host-platform }}"
        path: "./vendor/quickjs/libquickjs.a"
        retention-days: 1
        compression-level: 0
