name: "detect quickjs submodule update"
description: "detects whether quickjs's HEAD has new commits."
outputs:
  changed:
    description: "set to `true` if the upstream differs from the current submodule's HEAD."
    value: ${{ steps.check.outputs.changed }}

runs:
  using: "composite"
  steps:
    - name: "check upstream diff"
      id: "check"
      shell: "bash"
      run: |
        cd "./vendor/quickjs/"

        git fetch origin
        LOCAL=$(git rev-parse HEAD)
        REMOTE=$(git rev-parse origin/HEAD)

        if [ "$LOCAL" = "$REMOTE" ]; then
          echo "changed=false" >> "$GITHUB_OUTPUT"
        else
          echo "changed=true" >> "$GITHUB_OUTPUT"
        fi
